export const cropProfiles = [
  {
    crop: 'Soybean',
    seasons: ['kharif'],
    soilTypes: ['black_soil', 'alluvial_soil'],
    phRange: [6.0, 7.5],
    rainfallRange: [80, 180],
    tempRange: [24, 32],
    humidityRange: [60, 85],
    waterNeed: 'medium',
    durationDays: 105,
    profitabilityScore: 76,
    sustainabilityScore: 86,
    preferredNpk: { n: 65, p: 45, k: 40 },
    rotationBonus: ['onion', 'wheat'],
    actions: [
      'Use certified seeds before the first steady rains.',
      'Avoid waterlogging during early growth.',
      'Monitor for yellow mosaic symptoms from week 4.',
    ],
  },
  {
    crop: 'Maize',
    seasons: ['kharif', 'rabi'],
    soilTypes: ['alluvial_soil', 'black_soil', 'loamy_soil'],
    phRange: [5.8, 7.2],
    rainfallRange: [60, 140],
    tempRange: [20, 31],
    humidityRange: [50, 80],
    waterNeed: 'medium',
    durationDays: 110,
    profitabilityScore: 72,
    sustainabilityScore: 70,
    preferredNpk: { n: 80, p: 50, k: 45 },
    rotationBonus: ['soybean'],
    actions: [
      'Prepare raised rows for drainage.',
      'Plan split nitrogen application instead of one heavy dose.',
      'Scout for fall armyworm after germination.',
    ],
  },
  {
    crop: 'Cotton',
    seasons: ['kharif'],
    soilTypes: ['black_soil'],
    phRange: [6.2, 8.0],
    rainfallRange: [60, 120],
    tempRange: [24, 35],
    humidityRange: [45, 75],
    waterNeed: 'medium',
    durationDays: 170,
    profitabilityScore: 82,
    sustainabilityScore: 62,
    preferredNpk: { n: 70, p: 40, k: 50 },
    rotationBonus: ['wheat'],
    actions: [
      'Use pest monitoring traps from the first month.',
      'Avoid excess nitrogen to limit vegetative overgrowth.',
      'Plan timely bollworm scouting.',
    ],
  },
  {
    crop: 'Rice',
    seasons: ['kharif'],
    soilTypes: ['alluvial_soil', 'clay_soil'],
    phRange: [5.5, 7.0],
    rainfallRange: [120, 260],
    tempRange: [24, 34],
    humidityRange: [65, 90],
    waterNeed: 'high',
    durationDays: 125,
    profitabilityScore: 74,
    sustainabilityScore: 58,
    preferredNpk: { n: 85, p: 45, k: 45 },
    rotationBonus: ['pulses'],
    actions: [
      'Transplant only after field water control is ready.',
      'Maintain shallow standing water, not deep flooding.',
      'Watch for blast in humid spells.',
    ],
  },
  {
    crop: 'Wheat',
    seasons: ['rabi'],
    soilTypes: ['alluvial_soil', 'loamy_soil'],
    phRange: [6.0, 7.8],
    rainfallRange: [30, 80],
    tempRange: [12, 25],
    humidityRange: [40, 70],
    waterNeed: 'medium',
    durationDays: 120,
    profitabilityScore: 68,
    sustainabilityScore: 72,
    preferredNpk: { n: 70, p: 45, k: 35 },
    rotationBonus: ['soybean'],
    actions: [
      'Sow after adequate soil moisture is available.',
      'Use timely irrigation at crown root initiation stage.',
      'Monitor rust during cool humid conditions.',
    ],
  },
  {
    crop: 'Tomato',
    seasons: ['rabi', 'zaid'],
    soilTypes: ['loamy_soil', 'alluvial_soil'],
    phRange: [6.0, 7.0],
    rainfallRange: [40, 100],
    tempRange: [18, 28],
    humidityRange: [50, 75],
    waterNeed: 'medium',
    durationDays: 95,
    profitabilityScore: 84,
    sustainabilityScore: 66,
    preferredNpk: { n: 60, p: 50, k: 60 },
    rotationBonus: ['soybean'],
    actions: [
      'Use staking and airflow management early.',
      'Irrigate evenly and avoid leaf wetness late in the day.',
      'Inspect lower leaves twice a week for blight symptoms.',
    ],
  },
  {
    crop: 'Onion',
    seasons: ['rabi'],
    soilTypes: ['alluvial_soil', 'loamy_soil'],
    phRange: [6.0, 7.5],
    rainfallRange: [30, 70],
    tempRange: [15, 26],
    humidityRange: [45, 70],
    waterNeed: 'low',
    durationDays: 110,
    profitabilityScore: 81,
    sustainabilityScore: 75,
    preferredNpk: { n: 55, p: 40, k: 50 },
    rotationBonus: ['soybean'],
    actions: [
      'Ensure fine tilth before transplanting.',
      'Keep irrigation light but regular during bulb formation.',
      'Watch for thrips during dry hot conditions.',
    ],
  },
]
